apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginMinimalistMoments
spec:
  enabled: true
  requires: ">=2.22.0"
  author:
    name: 恪勤
    website: https://github.com/iszkq
  logo: logo.svg
  configMapName: plugin-minimalist-moments-configmap
  settingName: plugin-minimalist-moments-settings
  homepage: https://github.com/iszkq/halo-plugin-Minimalist
  repo: https://github.com/iszkq/halo-plugin-Minimalist
  issues: https://github.com/iszkq/halo-plugin-Minimalist/issues
  displayName: "Minimalist 瞬间"
  description: "Minimalist 定制版瞬间插件，内置前台渲染页面，支持图文、视频、音频、评论与时间流展示。"
  pluginDependencies:
    "PluginFeed?": ">=1.4.0"
